swagger: '2.0'
info:
  title: User API
  version: '1.0'
paths:
  /users:
    post:
      summary: Create a new user
      parameters:
        - name: name
          in: formData
          type: string
          required: true
          description: The name of the user
        - name: age
          in: formData
          type: integer
          required: true
          description: The age of the user
      responses:
        '201':
          description: The user was created successfully
        '400':
          description: Invalid request parameters
definitions:
  User:
    type: object
    properties:
      name:
        type: string
      age:
        type: integer
